(use-package! eaf)
;; (use-package! eaf-evil
;;   :config
;;   (define-key key-translation-map (kbd "SPC")
;;       (lambda (prompt)
;;         (if (derived-mode-p 'eaf-mode)
;;             (pcase eaf--buffer-app-name
;;               ("browser" (if  eaf-buffer-input-focus
;;                              (kbd "SPC")
;;                            (kbd eaf-evil-leader-key)))
;;               ("pdf-viewer" (kbd eaf-evil-leader-key))
;;               ("image-viewer" (kbd eaf-evil-leader-key))
;;               (_  (kbd "SPC")))
;;           (kbd "SPC")))))
(use-package! eaf-all-the-icons)
;; apps
(use-package! eaf-browser)
(use-package! eaf-jupyter)
(use-package! eaf-browser)
(use-package! eaf-airshare)
(use-package! eaf-file-browser)
(use-package! eaf-file-manager)
(use-package! eaf-file-sender)
(use-package! eaf-music-player)
(use-package! eaf-system-monitor)
(use-package! eaf-mindmap)
(use-package! eaf-org-previewer)
(use-package! eaf-terminal)
(use-package! eaf-netease-cloud-music)
(use-package! eaf-video-player)
(use-package! eaf-image-viewer)
(use-package! eaf-pdf-viewer)
(use-package! eaf-markdown-previewer)
(use-package! eaf-camera)
;; (use-package! eaf-demo)
;; (use-package! eaf-vue-demo)

(use-package! eaf-evil)
(setq eaf-evil-leader-key "SPC")
