(use-package! eaf)

;; apps
(use-package! eaf-browser)
(use-package! eaf-jupyter)
(use-package! eaf-browser)
(use-package! eaf-airshare)
(use-package! eaf-file-browser)
(use-package! eaf-file-manager)
(use-package! eaf-file-sender)
(use-package! eaf-music-player)
(use-package! eaf-system-monitor)
(use-package! eaf-mindmap)
(use-package! eaf-org-previewer)
(use-package! eaf-terminal)
(use-package! eaf-netease-cloud-music)
(use-package! eaf-video-player)
(use-package! eaf-image-viewer)
;; (use-package! eaf-demo)
;; (use-package! eaf-vue-demo)
(use-package! eaf-pdf-viewer)
(use-package! eaf-markdown-previewer)
(use-package! eaf-camera)
